[package]
name = "rbst328"
version = "0.1.0"
edition = "2024"

license = "AGPL-3.0-or-later"
description = "An ordered Map based on a self-balancing AVL Binary Search Tree with serialization support and no dependencies outside std"
repository = "https://github.com/msaw328/rbst328"
readme = "README.md"
keywords = ["data-structures", "binary-search-tree", "map", "collection"]
categories = ["algorithms", "data-structures"]

exclude = ["examples/", ".github"]

publish = false

[dev-dependencies]
# TODO: serde_json is only needed for examples
# If exampels are moved into separate bin targets,
# then serde_json could stop polluting dependencies of the global lib
serde_json = "1.0.149"
serde_test = "1.0.177"

[dependencies]
serde_core = { version = "1.0.228", optional = true }

[features]
serde = ["dep:serde_core"]
